export const CATEGORY_GUIDE = [
  {
    id: 1,
    short: "External",
    name: "The world outside the plan",
    question: "Has the world around this strategy moved?",
    why: "A plan written for one climate, one market, or one hazard mix can become the wrong plan without anyone missing a deadline.",
    looksFor: "Hazard trends, climate shifts, economic shocks, neighbouring conflicts, new diseases, demographic change.",
    example: "Romania: is flood still the main loss driver, or has the climate envelope in Annex 2 already broken?",
    ifEmpty: "You are not watching the outside world. A quiet year can still be the year the envelope moved.",
  },
  {
    id: 2,
    short: "Technology",
    name: "The systems the plan depends on",
    question: "Do the tools and data this plan needs still work?",
    why: "Modern strategies rest on platforms: warning, risk maps, loss registers. If those rot, the text is theatre.",
    looksFor: "Data platforms, early-warning systems, digital public infrastructure, cyber incidents, completeness of records.",
    example: "Romania: is DesInventar RO complete enough to steer investment, or is it an archive?",
    ifEmpty: "The plan names systems and nobody is checking whether they are alive.",
  },
  {
    id: 3,
    short: "Assumptions",
    name: "The story of how change happens",
    question: "Is the plan’s own story still true?",
    why: "Every strategy assumes a chain: if we do X, Y will follow. When that chain is false, more activity will not save the document.",
    looksFor: "The theory of change, “if we build it they will use it,” calendar-only review, implicit bets the authors never wrote down.",
    example: "Romania: is a three-year action-plan cycle enough, or does a major event need a legal hook to reopen the strategy?",
    ifEmpty: "You have not named the bets. The document is being treated as a to-do list.",
  },
  {
    id: 4,
    short: "Delivery",
    name: "Whether the work is getting done",
    question: "Are we doing what we said we would do?",
    why: "This is ordinary monitoring. It matters. It is not the same as asking whether the plan is still the right plan.",
    looksFor: "Outputs, milestones, annex lines, delayed studies, slipped trainings.",
    example: "Romania: Annex 1 completion against the published timetable.",
    ifEmpty: "Nobody is scoring the published plan. Delivery is not rated, not green.",
  },
  {
    id: 5,
    short: "Resources",
    name: "Money and people",
    question: "Is the money and the capacity still there?",
    why: "A plan that outlives its budget is a wish. Staff and absorption capacity are as real as appropriations.",
    looksFor: "Funding sunsets, successor windows, vacancy, county absorption, counterpart funds.",
    example: "Romania: PNRR / MFF money running out at the end of 2027.",
    ifEmpty: "The fiscal cliff will arrive whether or not you named it.",
  },
  {
    id: 6,
    short: "Mandate",
    name: "Who is allowed to act",
    question: "Does the coordinating body still have the power — and does it use it?",
    why: "A strategy without a sitting platform, or whose legal frame forbids the action it promises, cannot be delivered by effort alone.",
    looksFor: "Coordinating platforms, legal instruments, ministerial honour, machinery of government.",
    example: "Romania: does PNRRD still sit, and does HG 557/2016 actually allow Build Back Better?",
    ifEmpty: "The organogram is unwatched. That is how a strategy dies quietly.",
  },
  {
    id: 7,
    short: "Legitimacy",
    name: "Who actually benefits",
    question: "Do the people named in the plan actually receive what it promises?",
    why: "Coverage averages hide exclusion. A warning that reaches the county seat and not the named vulnerable group is a failed measure, not a communications issue.",
    looksFor: "Uptake, trust, distributional effects, warning reach, who is left out.",
    example: "Romania: does impact-based warning reach named vulnerable groups, or only a county average?",
    ifEmpty: "The plan claims equity and nobody is measuring who is missed.",
  },
  {
    id: 8,
    short: "Risks",
    name: "Events that should reopen the document",
    question: "Has a threshold been crossed that the plan itself cannot absorb?",
    why: "Some events are not “more of the same.” They are reasons to rewrite, not to file an after-action report.",
    looksFor: "Losses as a share of GDP, design events, compound crises, red lines agreed in advance.",
    example: "Romania: direct damages as a share of GDP, or a Vrancea-class earthquake.",
    ifEmpty: "There is no agreed red line. A disaster will be treated as weather.",
  },
  {
    id: 9,
    short: "Evidence",
    name: "What others have learned",
    question: "Has new evidence, a neighbour’s practice, or a binding rule made our text outdated?",
    why: "A national strategy does not live alone. EU instruments, Sendai successors, and peer evaluations can make yesterday’s annex illegal or merely foolish.",
    looksFor: "New evaluations, peer practice, adjacent strategies, binding regional instruments.",
    example: "Romania: alignment with Sendai and the EU Floods Directive — and whether a successor changes the indicator set.",
    ifEmpty: "You will learn about a binding change from a letter, not from a watchpoint.",
  },
  {
    id: 10,
    short: "Opportunity",
    name: "Windows you would regret missing",
    question: "Is there a new option that would change what this plan should do?",
    why: "Living documents are not only about threat. A new fund, a new instrument, a partnership window can justify an amendment without anything having failed.",
    looksFor: "New funds, solidarity windows, technology options, coalitions.",
    example: "Romania: a new EU DRR or solidarity instrument that could fund a stalled Annex 1 package.",
    ifEmpty: "The plan can only say no. It has no way to say yes to a new window.",
  },
] as const;

export type CategoryGuide = (typeof CATEGORY_GUIDE)[number];

export function categoryGuide(id: number): CategoryGuide {
  return CATEGORY_GUIDE.find((c) => c.id === id) ?? CATEGORY_GUIDE[0]!;
}
