import type { Intensity } from "./taxonomy";

type SeedAssumption = {
  claim: string;
  origin: "stated" | "implicit";
  status: "holding" | "weakening" | "broken" | "untested";
  implied_intensity: Exclude<Intensity, "no-change">;
  owner_label: string;
  sort_order: number;
};

type SeedSignal = {
  name: string;
  category: number;
  secondary_category: number | null;
  layer: "sentinel" | "rotating" | "interrupt";
  materiality: number;
  velocity: number;
  confidence: number;
  cadence: string;
  baseline: string;
  current_value: string;
  unit: string;
  threshold_watch: string;
  threshold_amend: string;
  threshold_refresh: string;
  threshold_reset: string;
  false_positive_guard: string;
  owner_label: string;
  links: number[];
};

export const ROMANIA_SEED = {
  strategy: {
    title: "Romania National Disaster Risk Reduction Strategy 2024–2035",
    domain: "Disaster risk reduction",
    jurisdiction: "Romania",
    language: "English",
    vision:
      "A living national DRR strategy that treats Sendai outcomes as the north star, while watching the conditions under which the strategy itself would need to be amended, refreshed, or reset.",
    horizon_start: "2024-01-01",
    horizon_end: "2035-12-31",
    delivery_rag: "amber" as const,
    delivery_basis:
      "2025 PNRRD progress note: Annex 1 studies and national-level measures delivered on the published calendar; county-level actions and the DesInventar rollout slipping by two or more quarters.",
    delivery_source: "PNRRD annual progress note 2025",
    delivery_as_of: "2025-12-31",
  },
  assumptions: [
    {
      claim:
        "Better multi-hazard understanding (RO-RISK, DesInventar RO, INFORM) will change investment and preparedness decisions — not merely produce more studies.",
      origin: "stated",
      status: "untested",
      implied_intensity: "refresh",
      owner_label: "IGSU / PNRRD",
      sort_order: 1,
    },
    {
      claim: "PNRRD remains a functioning coordinating platform with regular sittings and a mandate that ministries honour.",
      origin: "implicit",
      status: "untested",
      implied_intensity: "reset",
      owner_label: "PNRRD secretariat",
      sort_order: 2,
    },
    {
      claim:
        "A three-year action-plan cycle plus annual reporting is sufficient; the strategy itself does not need event-driven revision.",
      origin: "implicit",
      status: "weakening",
      implied_intensity: "amend",
      owner_label: "Strategy unit",
      sort_order: 3,
    },
    {
      claim: "PNRR and MFF 2021–2027 financing will carry the action plan past 2027 without a fiscal cliff.",
      origin: "implicit",
      status: "weakening",
      implied_intensity: "refresh",
      owner_label: "Finance / MAI",
      sort_order: 4,
    },
    {
      claim: "The legal frame (including HG 557/2016) allows Build Back Better after a major event.",
      origin: "stated",
      status: "untested",
      implied_intensity: "amend",
      owner_label: "Legal / MAI",
      sort_order: 5,
    },
    {
      claim: "Flood remains the operationally dominant loss driver; the Vrancea seismic tail does not require a different instrument mix.",
      origin: "implicit",
      status: "holding",
      implied_intensity: "refresh",
      owner_label: "IGSU",
      sort_order: 6,
    },
    {
      claim: "Impact-based early warning reaches named vulnerable groups, not only county average coverage.",
      origin: "stated",
      status: "untested",
      implied_intensity: "amend",
      owner_label: "ANM / IGSU",
      sort_order: 7,
    },
    {
      claim: "Sendai impact indicators (deaths, affected people, damages as % GDP) are the right strategy-validity north star.",
      origin: "stated",
      status: "holding",
      implied_intensity: "watch",
      owner_label: "PNRRD",
      sort_order: 8,
    },
    {
      claim: "Municipal and county absorption capacity can deliver the Annex 1 action plan on the published timetable.",
      origin: "implicit",
      status: "untested",
      implied_intensity: "amend",
      owner_label: "Local government",
      sort_order: 9,
    },
    {
      claim: "Climate and hazard baselines in Annex 2 remain a valid envelope through 2030.",
      origin: "implicit",
      status: "holding",
      implied_intensity: "refresh",
      owner_label: "ANM / researchers",
      sort_order: 10,
    },
    {
      claim: "IGSU can coordinate across ministries without a machinery-of-government rewrite.",
      origin: "implicit",
      status: "untested",
      implied_intensity: "reset",
      owner_label: "MAI",
      sort_order: 11,
    },
    {
      claim: "RO-RISK, DesInventar RO and INFORM stay current enough to be production systems, not archives.",
      origin: "stated",
      status: "untested",
      implied_intensity: "amend",
      owner_label: "IGSU / data unit",
      sort_order: 12,
    },
  ] satisfies SeedAssumption[],
  signals: [
    {
      name: "DesInventar RO completeness",
      category: 2,
      secondary_category: 3,
      layer: "sentinel",
      materiality: 5,
      velocity: 3,
      confidence: 2,
      cadence: "monthly",
      baseline: "System specified in Annex 1 (A1.2); completeness not baselined",
      current_value: "NO BASELINE",
      unit: "",
      threshold_watch: "Any county with >30 day reporting lag",
      threshold_amend: "National completeness < 80% of events",
      threshold_refresh: "System unused for a full reporting year",
      threshold_reset: "",
      false_positive_guard: "A single late county report is not a strategy failure",
      owner_label: "IGSU",
      links: [1, 12],
    },
    {
      name: "RO-RISK platform age",
      category: 2,
      secondary_category: 9,
      layer: "sentinel",
      materiality: 5,
      velocity: 2,
      confidence: 3,
      cadence: "quarterly",
      baseline: "Named production system for Objective 1",
      current_value: "In service (refresh age unknown)",
      unit: "months",
      threshold_watch: "No model refresh in 18 months",
      threshold_amend: "No refresh in 24 months, or major outage > 14 days",
      threshold_refresh: "Platform superseded or vendor lock-in blocks update",
      threshold_reset: "",
      false_positive_guard: "Scheduled maintenance is not obsolescence",
      owner_label: "IGSU",
      links: [1, 12],
    },
    {
      name: "PNRRD sitting frequency",
      category: 6,
      secondary_category: 5,
      layer: "sentinel",
      materiality: 5,
      velocity: 3,
      confidence: 3,
      cadence: "quarterly",
      baseline: "Chapter 8: annual PNRRD reporting",
      current_value: "Calendar in force",
      unit: "sittings / year",
      threshold_watch: "< 2 substantive sittings in 12 months",
      threshold_amend: "6 months without a sitting",
      threshold_refresh: "Platform exists on paper only",
      threshold_reset: "Coordinating mandate withdrawn",
      false_positive_guard: "A postponed meeting with a dated replacement is not failure",
      owner_label: "PNRRD",
      links: [2, 11],
    },
    {
      name: "Direct disaster damages as % of GDP",
      category: 8,
      secondary_category: 4,
      layer: "sentinel",
      materiality: 5,
      velocity: 5,
      confidence: 3,
      cadence: "event-driven",
      baseline: "Sendai C-2; flood 1990–2020: 48 events, 443 deaths",
      current_value: "0.18 (illustrative last-year proxy)",
      unit: "% GDP",
      threshold_watch: "0.30",
      threshold_amend: "0.50",
      threshold_refresh: "1.0 or a Vrancea-class event",
      threshold_reset: "Compound event that falsifies the four-objective set",
      false_positive_guard: "Do not treat a single local flash flood as national strategy failure",
      owner_label: "PNRRD / finance",
      links: [8, 6],
    },
    {
      name: "Post-2027 DRR funding status",
      category: 5,
      secondary_category: 6,
      layer: "sentinel",
      materiality: 5,
      velocity: 2,
      confidence: 2,
      cadence: "quarterly",
      baseline: "Action plan financed under PNRR / MFF 2021–2027",
      current_value: "Cliff dated 2027-12-31",
      unit: "",
      threshold_watch: "No successor envelope 18 months before cliff",
      threshold_amend: "Successor < 60% of current envelope",
      threshold_refresh: "No successor at cliff",
      threshold_reset: "",
      false_positive_guard: "A delayed but signed successor is an amend, not a refresh",
      owner_label: "Finance",
      links: [4],
    },
    {
      name: "Warning reach to named vulnerable groups",
      category: 7,
      secondary_category: 2,
      layer: "sentinel",
      materiality: 4,
      velocity: 3,
      confidence: 2,
      cadence: "monthly",
      baseline: "Impact-based warning planned; group-level reach not baselined",
      current_value: "NO BASELINE",
      unit: "%",
      threshold_watch: "A named group unreached in an exercise",
      threshold_amend: "A named group unreached in a real event",
      threshold_refresh: "Repeated exclusion across two events",
      threshold_reset: "",
      false_positive_guard: "Channel outage of minutes during a drill is not exclusion",
      owner_label: "ANM / IGSU",
      links: [7],
    },
    {
      name: "Vrancea IMR-100 damage envelope",
      category: 8,
      secondary_category: 1,
      layer: "sentinel",
      materiality: 5,
      velocity: 1,
      confidence: 3,
      cadence: "annual",
      baseline: "Annex 2: IMR-100 ≈ €7.6bn",
      current_value: "7.6",
      unit: "€ bn",
      threshold_watch: "Updated model > 20% above baseline",
      threshold_amend: "Envelope requires a different instrument mix",
      threshold_refresh: "Seismic tail dominates the investment case",
      threshold_reset: "",
      false_positive_guard: "Inflation rebasing without a new hazard model is not a trigger",
      owner_label: "INFP / IGSU",
      links: [6, 10],
    },
    {
      name: "Build Back Better legal barrier",
      category: 6,
      secondary_category: 9,
      layer: "sentinel",
      materiality: 4,
      velocity: 2,
      confidence: 3,
      cadence: "annual",
      baseline: "Strategy flags legal barriers to BBB",
      current_value: "Barrier still present",
      unit: "",
      threshold_watch: "No draft amendment in two years",
      threshold_amend: "Court or statute blocks a BBB reconstruction",
      threshold_refresh: "Post-disaster rebuild locked to like-for-like",
      threshold_reset: "",
      false_positive_guard: "A single contested permit is not a legal-frame failure",
      owner_label: "Legal",
      links: [5],
    },
    {
      name: "Annex 1 output completion vs plan",
      category: 4,
      secondary_category: null,
      layer: "rotating",
      materiality: 3,
      velocity: 2,
      confidence: 4,
      cadence: "quarterly",
      baseline: "21 progress indicators; evaluate at end of implementation period",
      current_value: "On published calendar (amber)",
      unit: "",
      threshold_watch: "Any specific objective > 12 months late",
      threshold_amend: "Two specific objectives stalled",
      threshold_refresh: "",
      threshold_reset: "",
      false_positive_guard: "A slipped study with a dated replacement is watch, not amend",
      owner_label: "IGSU",
      links: [9],
    },
    {
      name: "Climate-shifted flood frequency vs Annex 2",
      category: 1,
      secondary_category: 8,
      layer: "rotating",
      materiality: 4,
      velocity: 2,
      confidence: 3,
      cadence: "annual",
      baseline: "Annex 2: 48 flood disasters 1990–2020; 526 APSFRs; climate expected to raise winter/spring floods",
      current_value: "Envelope as published 2024",
      unit: "",
      threshold_watch: "Updated climate projection > 20% above Annex 2 frequency",
      threshold_amend: "New APSFR count or maps require different local packages",
      threshold_refresh: "Flood ceases to be the operationally dominant loss driver",
      threshold_reset: "",
      false_positive_guard: "A single wet year is not a climate-envelope break",
      owner_label: "ANM / ABA",
      links: [6, 10],
    },
    {
      name: "Event-driven reopening protocol in Chapter 8",
      category: 3,
      secondary_category: 6,
      layer: "rotating",
      materiality: 4,
      velocity: 2,
      confidence: 5,
      cadence: "annual",
      baseline: "Chapter 8: annual PNRRD reporting and 3-year action-plan revision only",
      current_value: "No event-driven protocol in the gazetted text",
      unit: "",
      threshold_watch: "Draft protocol circulated but not adopted",
      threshold_amend: "A major event occurs with no legal hook to reopen the strategy",
      threshold_refresh: "Calendar-only M&E survives a second major event",
      threshold_reset: "",
      false_positive_guard: "An internal IGSU after-action review is not a strategy reopening",
      owner_label: "Strategy unit",
      links: [3],
    },
    {
      name: "New EU / solidarity instrument option",
      category: 10,
      secondary_category: 5,
      layer: "rotating",
      materiality: 3,
      velocity: 2,
      confidence: 3,
      cadence: "annual",
      baseline: "EU Solidarity Fund used after 2010 floods; no standing option-value scan in the strategy",
      current_value: "Not scanned as a sentinel in the 2024 text",
      unit: "",
      threshold_watch: "New EU DRR or solidarity instrument opened for application",
      threshold_amend: "Instrument would fund > 20% of a stalled Annex 1 package",
      threshold_refresh: "A successor MFF window that the action plan cannot absorb without rewrite",
      threshold_reset: "",
      false_positive_guard: "A consultation paper is not an open window",
      owner_label: "Finance / MAI",
      links: [4, 10],
    },
    {
      name: "Adjacent EU / Sendai framework change",
      category: 9,
      secondary_category: 1,
      layer: "rotating",
      materiality: 3,
      velocity: 2,
      confidence: 4,
      cadence: "annual",
      baseline: "Aligned to Sendai and EU Floods Directive",
      current_value: "Aligned (2024 text)",
      unit: "",
      threshold_watch: "New EU instrument published",
      threshold_amend: "National text inconsistent with a binding instrument",
      threshold_refresh: "Sendai successor changes the indicator set",
      threshold_reset: "",
      false_positive_guard: "A consultation paper is not a binding change",
      owner_label: "Strategy unit",
      links: [8],
    },
  ] satisfies SeedSignal[],
  interrupts: [
    {
      name: "Major loss event",
      red_line: "A disaster with direct damages ≥ 0.5% of GDP, or a Vrancea-class earthquake.",
      category: 8,
    },
    {
      name: "Warning or risk-platform outage",
      red_line: "RO-RISK, DesInventar, or national warning unavailable for > 14 days, or a cyber incident that corrupts the loss record.",
      category: 2,
    },
    {
      name: "Coordinating body failure",
      red_line: "PNRRD does not sit for 6 months, or the coordinating mandate is withdrawn.",
      category: 6,
    },
  ],
  cliffs: [
    {
      name: "PNRR / MFF 2021–2027 funding sunset",
      cliff_date: "2027-12-31",
      kind: "fiscal" as const,
    },
    {
      name: "Mid-horizon strategy validity review",
      cliff_date: "2028-06-30",
      kind: "review" as const,
    },
    {
      name: "Next action-plan rewrite window",
      cliff_date: "2027-01-01",
      kind: "review" as const,
    },
  ],
  evidence: [
    {
      assumption_sort: 3,
      note: "Chapter 8 specifies annual PNRRD reporting and a 3-year action-plan revision. No event-driven protocol for reopening the strategy itself.",
      source_url: "",
      direction: "weakening" as const,
    },
    {
      assumption_sort: 4,
      note: "Action plan horizon (2024–2035) outlives MFF 2021–2027. Successor envelope is not named in the financing chapter.",
      source_url: "",
      direction: "weakening" as const,
    },
  ],
  excerpts: [
    {
      heading: "Chapter 8 — Monitoring and evaluation",
      body: "The strategy is monitored through annual reporting to PNRRD and a revision of the action plan every three years. Progress is assessed against the Sendai Framework indicators and the measures set out in Annex 1. The evaluation calendar follows the government planning cycle. The document does not provide a procedure for reopening the strategy itself after a major disaster, a legal change, or a funding cliff.",
    },
    {
      heading: "Annex 1 — Action plan 2024–2035",
      body: "Annex 1 assigns outputs, lead institutions, and indicative timelines for the period 2024–2035. Completion is reported annually. Several packages depend on PNRR and MFF 2021–2027 financing. The annex does not name a successor envelope after 2027, nor an event-driven rewrite of packages after a design-level earthquake or a loss exceeding a set share of GDP.",
    },
    {
      heading: "Annex 2 — Risk profile",
      body: "Floods dominate the operational loss record (48 flood disasters 1990–2020; 443 deaths). 526 areas of potentially significant flood risk (APSFRs) are identified. The Vrancea seismic source is treated as a tail risk with indicative average annual loss in the order of billions of euro. Climate projections are expected to raise winter and spring flood frequency. The strategy does not state a threshold at which an updated climate envelope would force a different instrument mix.",
    },
    {
      heading: "Financing and PNRR / MFF",
      body: "Implementation draws on the National Recovery and Resilience Plan and the Multiannual Financial Framework 2021–2027, together with the state budget and local contributions. The action-plan horizon extends to 2035. No named successor window is written into the financing chapter for the period after 31 December 2027.",
    },
    {
      heading: "Warning and vulnerable groups",
      body: "The strategy commits to impact-based early warning and to the protection of vulnerable groups. Coverage is discussed largely at county and national average. Named groups are not given a separate reach indicator, and RO-ALERT / warning performance is not given a sentinel with a false-positive guard.",
    },
  ],
  amendments: [
    {
      intensity: "amend" as const,
      location: "Chapter 8 — Monitoring and evaluation",
      original_excerpt:
        "The strategy is monitored through annual reporting to PNRRD and a revision of the action plan every three years. … The document does not provide a procedure for reopening the strategy itself after a major disaster.",
      proposed_text:
        "Keep annual PNRRD reporting and the three-year action-plan cycle. Add a new paragraph: “The strategy shall be reopened within 30 days if (a) direct disaster damages exceed 0.5% of GDP, (b) a Vrancea-class earthquake occurs, (c) RO-RISK, DesInventar or national warning is unavailable for more than 14 days, or (d) PNRRD does not sit for six months. The Strategy unit shall table an intensity recommendation (watch / amend / refresh / reset) to PNRRD.”",
      rationale:
        "The published M&E chapter is calendar-only. The load-bearing bet that this is sufficient is already weakening. This is an amend: the vision and Sendai north star stay; the revision protocol is added.",
      source: "monitor" as const,
    },
    {
      intensity: "amend" as const,
      location: "Financing chapter / Annex 1 packages that depend on PNRR and MFF 2021–2027",
      original_excerpt:
        "Implementation draws on the National Recovery and Resilience Plan and the Multiannual Financial Framework 2021–2027. … No named successor window is written into the financing chapter for the period after 31 December 2027.",
      proposed_text:
        "Insert a financing cliff clause: “By 30 June 2027 the Ministry of Finance and MAI shall publish the successor envelope for Annex 1 packages that currently depend on PNRR / MFF 2021–2027. Packages without a named successor by 31 December 2027 shall be marked for refresh of the action plan, not silent rollover.”",
      rationale:
        "The action plan runs to 2035; the money does not. This is the 31 December 2027 fiscal cliff. Amend the annex, do not wait for the 2028 validity review.",
      source: "monitor" as const,
    },
    {
      intensity: "watch" as const,
      location: "Annex 2 — Risk profile (flood envelope and APSFRs)",
      original_excerpt:
        "Floods dominate the operational loss record (48 flood disasters 1990–2020; 443 deaths). 526 APSFRs are identified. Climate projections are expected to raise winter and spring flood frequency.",
      proposed_text:
        "Do not rewrite Annex 2 yet. Add a monitoring sentence: “ANM / ABA shall report annually whether updated climate projections exceed the 2024 envelope by more than 20%, or whether the APSFR count requires different local packages. A single wet year is not a break of the envelope.”",
      rationale:
        "Flood remains the operationally dominant driver (assumption holding). Watch the envelope; amend maps if the 20% trigger is crossed.",
      source: "monitor" as const,
    },
    {
      intensity: "amend" as const,
      location: "Early warning / vulnerable groups section",
      original_excerpt:
        "The strategy commits to impact-based early warning and to the protection of vulnerable groups. Coverage is discussed largely at county and national average.",
      proposed_text:
        "Replace county-average coverage as the sole indicator with: “Share of named vulnerable groups reachable by impact-based warning within the standard (disaggregated, not county mean). Owner: IGSU / STS. Cadence: quarterly.”",
      rationale:
        "Averages hide exclusion. The legitimacy bet is untested because the published text never measured the group it names.",
      source: "monitor" as const,
    },
  ],
};
